language: node_js
node_js:
- lts/*
cache: npm
services:
- postgresql
before_script:
- psql -c 'CREATE DATABASE travis_ci_test;' -U postgres
deploy:
  provider: heroku
  api_key:
    secure: PGPEhnHRRj+v34Cb6Q9i4RgYbOH3nt1CzyRU9CpgVgQYCH6Pi6CK/UARbDy0lqH3fB+C0cAoiSL+KuvBGjcr1NJLmKoYzWCy/bhmVc8snLGSp6lhsiD9PousEd7t9NTPw35aufQg/uNXGuchGieYdZwQkdv4dkWwDfLMRbMwsedX5mGOy8A/JBtmWwR2sVdfrdGYirFYgBtvuQ3vPJFrXB2j9/GFjWk7C19eyzLrDvjXJY4PujwEKRhezKWjCT0LE/SuRRKwGiyer44OWPt4Z4pUjWcHAUlOFJRuW3gmJ0z52fEErTkwgVz3bGTZKhLMWRq7NGHdNKkswC1qG8T45IJm3z9lgjYtP2KRDtoAJ0NZbLVpFPe098CfQm4LM6sqVAJPKSCcWEbEyt4gfTmqgggpqscYY2P+I8YtT1xbWJIDmawG4rWdOQ71m0o7YwxqtZm/L+2LBp2xgfTCcP69k3AvV8OilhipRSGvCbOFGJCvyW4I1ilqZH4LS/xZEV1zb0vCuCrF3LQDy+XfEWTvQ5zsxvUYIJJ/ZWTFsv496EHW4f7oU4DO014f+2YfW2CUAG/Jiay1Gk9XClreuFpZ70SQDCJaQ2lB0y0oE7jMAHw1PSO3u+rKpuQirhshrmDsSZWZnaTt4gkwgGWEWGfxjZPj8cVia5rOUaMCyeXH8RI=
  app: penn-todo
  on:
    repo: BjornLuG/penn-todo
