language: node_js
node_js:
- lts/*
cache: npm
services:
- postgresql
before_script:
- psql -c 'CREATE DATABASE travis_ci_test;' -U postgres
deploy:
  provider: heroku
  api_key:
    secure: O+hfqSHLxResN0zxhwfOvYY5V9pw6Ib0UpskUBrnwjRQpCyG3z9HPiQ/ld2qfetdHPb4oeCE3qQigYkUvljBJylLFU6gNbUuckX1Vwuck/KSBvp2JH/ad6dc+OPvZssuO51BByicwrxZM/COmcC5t8RF3GGJBRIyPTE0I3qs01ZEak2hRYbpUuaIpy8wH/DvfuNgg/7YGqA6CDAfzVPDLnOBKKKU0DJ80TqTIzvtcDnLMPexLYEgjeZp3MefDkJTTQLHsQ61ohsieWmzVb4+nf5S23ugibV4WhjOWsvef0a8AtiCAPu9AaVRbkW3+Pd3cHJaALnTNb/Khj8Ns/jO9y2orNSGMEQiUY5/2IPgrvxFbpZ0c5tTnBhORR8bj1+WqwSUmYXVGvZHbxbzYOC6MVqjQplLAX7arQlQCpF7eTjlGCif3bv0ymttMdnbALIM3+8LlSNO2+D6IbueD4rYOR4cDmbw/QkNIAOVLCBFotKVobLtV4MhF1/Xv6nfFJc/2xqOL85h9DqPAWs1bUu3jClCtP/QN5+bqQZsZNdNqpWj3UPMPQAMyTflh5AaHCwhj7zOBDJM4mkgnOWumIiIrm8iG4b31DuvtcylDLPvBJBvIHuskG+oPMSOPFGY4oX5r5ukyEtlnHA3t1vDMq6u9aXg20OsZiY/kHDf/mUyLjI=
  app: penn-todo
