language: node_js
node_js:
- lts/*
cache: npm
services:
- postgresql
before_script:
- psql -c 'CREATE DATABASE travis_ci_test;' -U postgres
deploy:
  provider: heroku
  api_key:
    secure: NkyWIcxpsNjQlwEyIPIPJPMeloAplhorYjeMmevq3Qkwq+GUdhp4yNa12NBvAx4h8kbjTGn1mlnRpxkc4HNI8gV9yVQmvvsl3TsVoBSYvHNBl0Qf70stkqrzWir5WXnwsxbf+TIqQ3A13VB08WDza9n7OL0NlVUoDoT88DWz4G+ZrQUzgHnRtudOSIB1a5jqDBbRmgA/Ulw+cPu2NhhWh+rFqoi4Ll0YJtsWGpH28pkfXeadKZ8e0lhD78DGfu/GN+DRhqqvdnP81ALeN6kQQzqdRZNHOYTeJidp4Cm8OmggKk+hdacbnwtH0pV+DfiNscQSwGYRIKxptvklsdlwtl6b6XdJ//d3SW4AazhJRxrE7H3OPfklQNiqCK2VYgUxty8vCdXbM/FmTrLouoRaAIbaIkLFATxJm9mPGzriElcajkuQ5rWo6npdo+DBj7xvxY/hiOx0IDD5bBgtkr/76Jay/WeOQTEyAbYaqIt8bHwVsTIqD7jCyoQWia1azVD68DcanumoOANe3jbV/717FKcD6zJIBJ+duk5KVHIXsDzgsO0sL3lyvKMWkiqvn3mv4D0EGKfrXmQI/1IA0bgQFVJWNNvEqu86ne0DYZtLwjXRweCZXBen0gBnxSN3KFqya3ycyQPEVLuuuQkcVmnW1dvz9yLVajOH1KKJQNPgvvg=
  app: penn-todo
  on:
    repo: BjornLuG/penn-todo
